"""Read-only softcode corpus inventory helpers."""

from __future__ import annotations

import argparse
import os
import re
from collections import Counter
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

FileKind = Literal["softcode", "source_code", "data", "documentation", "unknown"]
UnitKind = Literal[
    "cmd",
    "fn",
    "map",
    "filter",
    "lock",
    "data",
    "doc",
    "raw",
    "unknown",
]

ATTRIBUTE_RE = re.compile(r"^\s*&(?P<name>[^\s=]+)\s+(?P<object>[^=]+?)=(?P<body>.*)$")

SKIPPED_DIRECTORY_NAMES = frozenset(
    {
        ".git",
        ".hg",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".svn",
        "__pycache__",
        "node_modules",
    }
)

SOFTCODE_SUFFIXES = frozenset({".mush"})
TEXT_SOFTCODE_SUFFIXES = frozenset({".txt", ".t"})
DOCUMENTATION_SUFFIXES = frozenset({".md", ".rst"})
SOURCE_CODE_SUFFIXES = frozenset(
    {
        ".c",
        ".css",
        ".h",
        ".in",
        ".js",
        ".php",
        ".pl",
        ".pm",
        ".py",
        ".sh",
        ".tpl",
    }
)
DATA_SUFFIXES = frozenset({".json", ".sql", ".xml", ".yaml", ".yml"})


@dataclass(frozen=True)
class CandidateSoftcodeUnit:
    source_path: Path
    line_number: int
    attribute_name: str
    object_ref: str
    body: str
    kind: UnitKind


@dataclass(frozen=True)
class InventoryFile:
    path: Path
    kind: FileKind
    candidate_units: tuple[CandidateSoftcodeUnit, ...]


@dataclass(frozen=True)
class SkippedDirectory:
    path: Path
    reason: str


@dataclass(frozen=True)
class InventoryRoot:
    path: Path
    exists: bool
    files: tuple[InventoryFile, ...] = ()
    skipped_directories: tuple[SkippedDirectory, ...] = ()

    @property
    def candidate_unit_count(self) -> int:
        return sum(len(file.candidate_units) for file in self.files)


@dataclass(frozen=True)
class SoftcodeInventory:
    roots: tuple[InventoryRoot, ...]

    @property
    def file_count(self) -> int:
        return sum(len(root.files) for root in self.roots)

    @property
    def candidate_unit_count(self) -> int:
        return sum(root.candidate_unit_count for root in self.roots)

    def file_kind_counts(self) -> Counter[str]:
        return Counter(file.kind for root in self.roots for file in root.files)

    def unit_kind_counts(self) -> Counter[str]:
        return Counter(
            unit.kind
            for root in self.roots
            for file in root.files
            for unit in file.candidate_units
        )


def collect_softcode_inventory(paths: Iterable[Path]) -> SoftcodeInventory:
    roots = tuple(_collect_root(path) for path in paths)
    return SoftcodeInventory(roots=roots)


def render_inventory_report(inventory: SoftcodeInventory) -> str:
    lines = [
        "# Softcode Inventory Report",
        "",
        "Generated by `collect_softcode_inventory`.",
        "",
        "## Summary",
        "",
        f"- Roots: {len(inventory.roots)}",
        f"- Files: {inventory.file_count}",
        f"- Candidate softcode units: {inventory.candidate_unit_count}",
        "",
        "## File Kinds",
        "",
    ]
    lines.extend(_counter_lines(inventory.file_kind_counts()))
    lines.extend(("", "## Candidate Unit Kinds", ""))
    lines.extend(_counter_lines(inventory.unit_kind_counts()))
    lines.extend(("", "## Roots", ""))
    for root in inventory.roots:
        status = "present" if root.exists else "missing"
        lines.extend(
            (
                f"### `{root.path}`",
                "",
                f"- Status: {status}",
                f"- Files: {len(root.files)}",
                f"- Candidate softcode units: {root.candidate_unit_count}",
                f"- Skipped directories: {len(root.skipped_directories)}",
                "",
            )
        )
        if root.skipped_directories:
            lines.append("Skipped:")
            lines.append("")
            for skipped in root.skipped_directories:
                lines.append(f"- `{skipped.path}`: {skipped.reason}")
            lines.append("")
        if root.files:
            lines.append("File kind counts:")
            lines.append("")
            lines.extend(_counter_lines(Counter(file.kind for file in root.files)))
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_inventory_report(inventory: SoftcodeInventory, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_inventory_report(inventory), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Inventory softcode corpora.")
    parser.add_argument("paths", nargs="+", type=Path)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args(argv)

    inventory = collect_softcode_inventory(args.paths)
    report = render_inventory_report(inventory)
    if args.report is None:
        print(report, end="")
    else:
        write_inventory_report(inventory, args.report)
    return 0


def _collect_root(path: Path) -> InventoryRoot:
    resolved = path.resolve()
    if not resolved.exists():
        return InventoryRoot(path=resolved, exists=False)
    if resolved.is_file():
        return InventoryRoot(
            path=resolved,
            exists=True,
            files=(_inspect_file(resolved),),
        )

    files: list[InventoryFile] = []
    skipped_directories: list[SkippedDirectory] = []
    for dirpath, dirnames, filenames in os.walk(resolved):
        current_dir = Path(dirpath)
        kept_dirnames: list[str] = []
        for dirname in sorted(dirnames):
            if dirname in SKIPPED_DIRECTORY_NAMES:
                skipped_directories.append(
                    SkippedDirectory(
                        path=current_dir / dirname,
                        reason="standard generated or VCS directory",
                    )
                )
            else:
                kept_dirnames.append(dirname)
        dirnames[:] = kept_dirnames
        for filename in sorted(filenames):
            files.append(_inspect_file(current_dir / filename))
    return InventoryRoot(
        path=resolved,
        exists=True,
        files=tuple(sorted(files, key=lambda file: str(file.path).casefold())),
        skipped_directories=tuple(skipped_directories),
    )


def _inspect_file(path: Path) -> InventoryFile:
    text = _read_text_if_candidate(path)
    units = _candidate_units(path, text) if text is not None else ()
    return InventoryFile(
        path=path,
        kind=_classify_file(path, text, units),
        candidate_units=units,
    )


def _read_text_if_candidate(path: Path) -> str | None:
    suffix = path.suffix.casefold()
    if suffix not in (
        SOFTCODE_SUFFIXES
        | TEXT_SOFTCODE_SUFFIXES
        | DOCUMENTATION_SUFFIXES
        | SOURCE_CODE_SUFFIXES
        | DATA_SUFFIXES
    ):
        return None
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def _candidate_units(path: Path, text: str) -> tuple[CandidateSoftcodeUnit, ...]:
    units: list[CandidateSoftcodeUnit] = []
    for line_number, line in enumerate(text.splitlines(), start=1):
        match = ATTRIBUTE_RE.match(line)
        if match is None:
            continue
        attribute_name = match.group("name")
        units.append(
            CandidateSoftcodeUnit(
                source_path=path,
                line_number=line_number,
                attribute_name=attribute_name,
                object_ref=match.group("object").strip(),
                body=match.group("body"),
                kind=_classify_attribute(attribute_name),
            )
        )
    return tuple(units)


def _classify_attribute(attribute_name: str) -> UnitKind:
    normalized = attribute_name.upper()
    head = re.split(r"[.`_-]", normalized, maxsplit=1)[0]
    if head == "CMD":
        return "cmd"
    if head in {"FN", "FUN", "SUBFN"}:
        return "fn"
    if head == "MAP":
        return "map"
    if head == "FILTER":
        return "filter"
    if head == "LOCK" or "LOCK" in normalized:
        return "lock"
    if head == "DATA":
        return "data"
    if head in {"DOC", "HELP"}:
        return "doc"
    if normalized:
        return "unknown"
    return "raw"


def _classify_file(
    path: Path,
    text: str | None,
    units: tuple[CandidateSoftcodeUnit, ...],
) -> FileKind:
    suffix = path.suffix.casefold()
    name = path.name.casefold()
    if suffix in SOFTCODE_SUFFIXES:
        return "softcode"
    if suffix in TEXT_SOFTCODE_SUFFIXES and (units or _looks_like_softcode(text)):
        return "softcode"
    if suffix in DOCUMENTATION_SUFFIXES or name.startswith(("readme", "changes")):
        return "documentation"
    if suffix in DATA_SUFFIXES:
        return "data"
    if suffix in SOURCE_CODE_SUFFIXES:
        return "source_code"
    if units:
        return "softcode"
    return "unknown"


def _looks_like_softcode(text: str | None) -> bool:
    if text is None:
        return False
    for line in text.splitlines():
        stripped = line.lstrip()
        if stripped.startswith(("&", "@", "th ", "think ", "test(")):
            return True
    return False


def _counter_lines(counter: Counter[str]) -> list[str]:
    if not counter:
        return ["- none"]
    return [f"- {key}: {counter[key]}" for key in sorted(counter)]


if __name__ == "__main__":
    raise SystemExit(main())
