"""Softcode source-unit extraction."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections import Counter
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from mushy_peas.softcode.inventory import (
    FileKind,
    UnitKind,
    classify_file_path,
    collect_softcode_inventory,
    line_spans,
    parse_attribute_install_line,
    read_text_if_candidate,
)
from mushy_peas.softcode.model import Span

INSTALL_COMMAND_RE = re.compile(
    r"^\s*@(?P<name>[A-Za-z][A-Za-z0-9_+/-]*)\s+(?P<object>[^=]+?)=(?P<body>.*)$"
)


@dataclass(frozen=True)
class SoftcodeUnit:
    id: str
    source_path: Path
    source_kind: FileKind
    profile_hint: str
    object_ref: str | None
    attribute_name: str | None
    attribute_kind: UnitKind
    command_pattern: str | None
    body: str
    source_span: Span
    line_number: int

    def to_json(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "source_path": str(self.source_path),
            "source_kind": self.source_kind,
            "profile_hint": self.profile_hint,
            "object_ref": self.object_ref,
            "attribute_name": self.attribute_name,
            "attribute_kind": self.attribute_kind,
            "command_pattern": self.command_pattern,
            "body": self.body,
            "source_span": {
                "start": self.source_span.start,
                "end": self.source_span.end,
            },
            "line_number": self.line_number,
        }


@dataclass(frozen=True)
class SoftcodeUnitCollection:
    units: tuple[SoftcodeUnit, ...]

    def kind_counts(self) -> Counter[str]:
        return Counter(unit.attribute_kind for unit in self.units)

    def source_kind_counts(self) -> Counter[str]:
        return Counter(unit.source_kind for unit in self.units)

    def to_json(self) -> dict[str, Any]:
        return {"units": [unit.to_json() for unit in self.units]}


def extract_softcode_units(paths: Iterable[Path]) -> SoftcodeUnitCollection:
    inventory = collect_softcode_inventory(paths)
    units: list[SoftcodeUnit] = []
    for root in inventory.roots:
        for file in root.files:
            if file.kind != "softcode":
                continue
            text = read_text_if_candidate(file.path)
            if text is None:
                continue
            units.extend(_extract_file_units(file.path, text))
    return SoftcodeUnitCollection(
        units=tuple(
            sorted(
                units,
                key=lambda unit: (
                    str(unit.source_path).casefold(),
                    unit.line_number,
                    unit.attribute_name or "",
                ),
            )
        ),
    )


def render_softcode_unit_report(collection: SoftcodeUnitCollection) -> str:
    lines = [
        "# Softcode Unit Report",
        "",
        "Generated by `extract_softcode_units`.",
        "",
        "## Summary",
        "",
        f"- Units: {len(collection.units)}",
        "",
        "## Source Kinds",
        "",
    ]
    lines.extend(_counter_lines(collection.source_kind_counts()))
    lines.extend(("", "## Attribute Kinds", ""))
    lines.extend(_counter_lines(collection.kind_counts()))
    return "\n".join(lines).rstrip() + "\n"


def write_softcode_unit_report(collection: SoftcodeUnitCollection, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_softcode_unit_report(collection), encoding="utf-8")


def write_softcode_units_json(collection: SoftcodeUnitCollection, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(collection.to_json(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Extract softcode source units.")
    parser.add_argument("paths", nargs="+", type=Path)
    parser.add_argument("--report", type=Path)
    parser.add_argument("--json", type=Path)
    args = parser.parse_args(argv)

    collection = extract_softcode_units(args.paths)
    if args.json is not None:
        write_softcode_units_json(collection, args.json)
    report = render_softcode_unit_report(collection)
    if args.report is None:
        print(report, end="")
    else:
        write_softcode_unit_report(collection, args.report)
    return 0


def _extract_file_units(path: Path, text: str) -> tuple[SoftcodeUnit, ...]:
    source_kind = classify_file_path(path, text)
    profile_hint = _profile_hint(path)
    units: list[SoftcodeUnit] = []
    spans = line_spans(text)
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        line_number = index + 1
        line = lines[index]
        span = spans[index]
        attribute = parse_attribute_install_line(path, line_number, span, line)
        if attribute is not None:
            body, source_span, next_index = _coalesce_attribute_body(
                lines,
                spans,
                index,
                attribute.body,
                attribute.source_span,
                path,
            )
            units.append(
                SoftcodeUnit(
                    id=_unit_id(path, line_number, attribute.attribute_name),
                    source_path=path,
                    source_kind=source_kind,
                    profile_hint=profile_hint,
                    object_ref=attribute.object_ref,
                    attribute_name=attribute.attribute_name,
                    attribute_kind=attribute.kind,
                    command_pattern=_command_pattern(attribute.kind, body),
                    body=body,
                    source_span=source_span,
                    line_number=line_number,
                )
            )
            index = next_index
        else:
            install_command = _parse_install_command_line(line)
            if install_command is not None:
                command_name, object_ref, command_body = install_command
                body, source_span, next_index = _coalesce_install_command_body(
                    lines,
                    spans,
                    index,
                    command_body,
                    span,
                    path,
                )
                units.append(
                    SoftcodeUnit(
                        id=_unit_id(path, line_number, f"@{command_name}"),
                        source_path=path,
                        source_kind=source_kind,
                        profile_hint=profile_hint,
                        object_ref=object_ref,
                        attribute_name=f"@{command_name.upper()}",
                        attribute_kind="cmd",
                        command_pattern=None,
                        body=body,
                        source_span=source_span,
                        line_number=line_number,
                    )
                )
                index = next_index
            elif line.strip():
                units.append(
                    SoftcodeUnit(
                        id=_unit_id(path, line_number, None),
                        source_path=path,
                        source_kind=source_kind,
                        profile_hint=profile_hint,
                        object_ref=None,
                        attribute_name=None,
                        attribute_kind="raw",
                        command_pattern=None,
                        body=line,
                        source_span=span,
                        line_number=line_number,
                    )
                )
                index += 1
            else:
                index += 1
    return tuple(units)


def _coalesce_attribute_body(
    lines: list[str],
    spans: tuple[Span, ...],
    index: int,
    body: str,
    source_span: Span,
    path: Path,
) -> tuple[str, Span, int]:
    next_index = index + 1
    if next_index >= len(lines):
        return body, source_span, next_index
    if body:
        if lines[next_index].strip() == "-":
            return body, Span(source_span.start, spans[next_index].end), next_index + 1
        return body, source_span, next_index

    continuation: list[str] = []
    scan_index = next_index
    while scan_index < len(lines):
        line = lines[scan_index]
        span = spans[scan_index]
        if line.strip() == "-":
            return (
                "\n".join(continuation),
                Span(source_span.start, span.end),
                scan_index + 1,
            )
        if parse_attribute_install_line(path, scan_index + 1, span, line) is not None:
            return body, source_span, next_index
        continuation.append(line)
        scan_index += 1
    return body, source_span, next_index


def _parse_install_command_line(line: str) -> tuple[str, str, str] | None:
    match = INSTALL_COMMAND_RE.match(line)
    if match is None:
        return None
    return (
        match.group("name"),
        match.group("object").strip(),
        match.group("body"),
    )


def _coalesce_install_command_body(
    lines: list[str],
    spans: tuple[Span, ...],
    index: int,
    body: str,
    source_span: Span,
    path: Path,
) -> tuple[str, Span, int]:
    return _coalesce_attribute_body(lines, spans, index, body, source_span, path)


def _unit_id(path: Path, line_number: int, attribute_name: str | None) -> str:
    key = f"{path.resolve().as_posix().casefold()}:{line_number}:{attribute_name or ''}"
    digest = hashlib.sha1(key.encode("utf-8")).hexdigest()[:16]
    return f"softcode:{digest}"


def _profile_hint(path: Path) -> str:
    parts = {part.casefold() for part in path.parts}
    if "wcnh" in parts:
        return "wcnh"
    if "mushcode" in parts:
        return "volund-mushcode"
    if "pennmush" in parts:
        return "pennmush-core"
    return "unknown"


def _command_pattern(kind: UnitKind, body: str) -> str | None:
    if kind != "cmd" or not body.startswith("$"):
        return None
    pattern, separator, _action = body.partition(":")
    if not separator:
        return None
    return pattern


def _counter_lines(counter: Counter[str]) -> list[str]:
    if not counter:
        return ["- none"]
    return [f"- {key}: {counter[key]}" for key in sorted(counter)]


if __name__ == "__main__":
    raise SystemExit(main())
