"""PennMUSH database constants."""

from typing import Final

OBJECT_TYPE_ROOM: Final[int] = 0x1
OBJECT_TYPE_THING: Final[int] = 0x2
OBJECT_TYPE_EXIT: Final[int] = 0x4
OBJECT_TYPE_PLAYER: Final[int] = 0x8
OBJECT_TYPE_GARBAGE: Final[int] = 0x10

CURRENT_DB_VERSION: Final[int] = 6

DBF_NO_CHAT_SYSTEM: Final[int] = 0x01
DBF_WARNINGS: Final[int] = 0x02
DBF_CREATION_TIMES: Final[int] = 0x04
DBF_NEW_STRINGS: Final[int] = 0x20
DBF_TYPE_GARBAGE: Final[int] = 0x40
DBF_SPLIT_IMMORTAL: Final[int] = 0x80
DBF_NO_TEMPLE: Final[int] = 0x100
DBF_LESS_GARBAGE: Final[int] = 0x200
DBF_AF_VISUAL: Final[int] = 0x400
DBF_VALUE_IS_COST: Final[int] = 0x800
DBF_LINK_ANYWHERE: Final[int] = 0x1000
DBF_NO_STARTUP_FLAG: Final[int] = 0x2000
DBF_AF_NODUMP: Final[int] = 0x8000
DBF_SPIFFY_LOCKS: Final[int] = 0x10000
DBF_NEW_FLAGS: Final[int] = 0x20000
DBF_NEW_POWERS: Final[int] = 0x40000
DBF_POWERS_LOGGED: Final[int] = 0x80000
DBF_LABELS: Final[int] = 0x100000
DBF_SPIFFY_AF_ANSI: Final[int] = 0x200000
DBF_HEAR_CONNECT: Final[int] = 0x400000
DBF_NEW_VERSIONS: Final[int] = 0x800000

CURRENT_MAIN_DB_FLAGS: Final[int] = (
    DBF_NO_CHAT_SYSTEM
    | DBF_WARNINGS
    | DBF_CREATION_TIMES
    | DBF_SPIFFY_LOCKS
    | DBF_NEW_STRINGS
    | DBF_TYPE_GARBAGE
    | DBF_SPLIT_IMMORTAL
    | DBF_NO_TEMPLE
    | DBF_LESS_GARBAGE
    | DBF_AF_VISUAL
    | DBF_VALUE_IS_COST
    | DBF_LINK_ANYWHERE
    | DBF_NO_STARTUP_FLAG
    | DBF_AF_NODUMP
    | DBF_NEW_FLAGS
    | DBF_NEW_POWERS
    | DBF_POWERS_LOGGED
    | DBF_LABELS
    | DBF_HEAR_CONNECT
    | DBF_NEW_VERSIONS
)

MAIL_FLAG_SUBJECT: Final[int] = 0x1
MAIL_FLAG_ALIASES: Final[int] = 0x2
MAIL_FLAG_NEW_EOD: Final[int] = 0x4
MAIL_FLAG_SENDER_CTIME: Final[int] = 0x8
MAIL_FLAGS_CURRENT: Final[int] = (
    MAIL_FLAG_SUBJECT
    | MAIL_FLAG_ALIASES
    | MAIL_FLAG_NEW_EOD
    | MAIL_FLAG_SENDER_CTIME
)

CHAT_FLAG_SPIFFY: Final[int] = 0x01
CHAT_FLAGS_CURRENT: Final[int] = CHAT_FLAG_SPIFFY

END_MARKER_CURRENT: Final[str] = "***END OF DUMP***"
END_MARKER_OLD: Final[str] = "*** END OF DUMP ***"
